# Generated by Django 4.1.3 on 2022-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translators',
            name='email',
            field=models.EmailField(default='123@mail.ru', help_text='Enter your e-mail', max_length=254),
        ),
        migrations.AddField(
            model_name='translators',
            name='phone',
            field=models.IntegerField(default='123', help_text='Enter your phone number'),
        ),
    ]
