# Generated by Django 4.1.3 on 2022-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_translators_email_translators_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='translators',
            name='languages',
            field=models.CharField(blank=True, help_text='Enter your working languages', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='translators',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your e-mail', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='translators',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Enter your phone number', null=True),
        ),
    ]
