# Generated by Django 4.1.3 on 2022-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_translators_languages_alter_translators_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'on progress'), ('d', 'delivered')], default='w', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, help_text='name of movie.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
