# Generated by Django 4.1.3 on 2022-11-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_duration_order_episode_order_rate_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.translators'),
        ),
    ]
