# Generated by Django 4.1.3 on 2022-11-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_translator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='movie_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.movietype'),
        ),
        migrations.AddField(
            model_name='order',
            name='translation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.translationtypes'),
        ),
    ]
