# Generated by Django 4.1.3 on 2022-11-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_movie_type_order_translation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.ForeignKey(blank=True, help_text='ru-en, en-ru, de-en etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.languagepairs'),
        ),
    ]
