# Generated by Django 4.1.3 on 2022-11-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
