# Generated by Django 4.1.3 on 2022-11-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_post_deadline_post_duration_post_episode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
