# Generated by Django 4.1.3 on 2022-11-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
        ('orders', '0017_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translators',
            name='user_name',
            field=models.OneToOneField(default='Karen', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
