# Generated by Django 4.1.3 on 2022-11-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
        ('orders', '0019_alter_translators_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='users.profile')),
            ],
        ),
    ]
