# Generated by Django 4.1.3 on 2022-12-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
